name: spys_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  meta: ^1.17.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.6.1
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  lints: ^5.0.0
  test: ^1.24.0
