name: spys_api_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  http: ^1.5.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  supabase_flutter: ^2.6.0
  uuid: ^3.0.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.6.1
  json_serializable: ^6.10.0
  lints: ^5.0.0
  test: ^1.26.3
