// // mock_orders.dart
// import '../../../shared/types/order.dart';

// final List<Order> mockOrders = [
//   Order(
//     id: "ORD-001",
//     customerEmail: "john.smith@email.com",
//     // kampus:"Centurion",
//     items: [
//       OrderItem(
//         id: "1",
//         name: "Caesar Salad",
//         quantity: 2,
//         price: 12.99,
//         status: OrderStatus.preparing,
//         scheduledDay: "Donderdag",
//       ),
//       OrderItem(
//         id: "2",
//         name: "Grilled Chicken",
//         quantity: 1,
//         price: 18.99,
//         status: OrderStatus.preparing,
//         scheduledDay: "Donderdag",
//       ),
//       OrderItem(
//         id: "3",
//         name: "Pasta Carbonara",
//         quantity: 1,
//         price: 16.99,
//         status: OrderStatus.pending,
//         scheduledDay: "Vrydag",
//       ),
//     ],
//     scheduledDays: ["Donderdag", "Vrydag"],
//     status: OrderStatus.preparing,
//     createdAt: DateTime.parse("2025-09-10T10:30:00Z"),
//     totalAmount: 48.97,
//   ),
//   Order(
//     id: "ORD-002",
//     customerEmail: "emily.johnson@email.com",
//     items: [
//       OrderItem(
//         id: "4",
//         name: "Margherita Pizza",
//         quantity: 1,
//         price: 14.99,
//         status: OrderStatus.delivered,
//         scheduledDay: "Donderdag",
//       ),
//       OrderItem(
//         id: "5",
//         name: "Tiramisu",
//         quantity: 2,
//         price: 8.99,
//         status: OrderStatus.delivered,
//         scheduledDay: "Donderdag",
//       ),
//     ],
//     scheduledDays: ["Donderdag"],
//     status: OrderStatus.delivered,
//     createdAt: DateTime.parse("2025-09-11T08:15:00Z"),
//     totalAmount: 32.97,
//   ),
//   Order(
//     id: "ORD-003",
//     customerEmail: "michael.brown@email.com",
//     items: [
//       OrderItem(
//         id: "6",
//         name: "Fish & Chips",
//         quantity: 2,
//         price: 15.99,
//         status: OrderStatus.outForDelivery,
//         scheduledDay: "Donderdag",
//       ),
//       OrderItem(
//         id: "7",
//         name: "Coleslaw",
//         quantity: 2,
//         price: 4.99,
//         status: OrderStatus.outForDelivery,
//         scheduledDay: "Donderdag",
//       ),
//     ],
//     scheduledDays: ["Donderdag"],
//     status: OrderStatus.outForDelivery,
//     createdAt: DateTime.parse("2025-09-11T11:45:00Z"),
//     totalAmount: 41.96,
//   ),
//   Order(
//     id: "ORD-004",
//     customerEmail: "sarah.davis@email.com",
//     items: [
//       OrderItem(
//         id: "8",
//         name: "Vegetarian Burger",
//         quantity: 1,
//         price: 13.99,
//         status: OrderStatus.pending,
//         scheduledDay: "Vrydag",
//       ),
//       OrderItem(
//         id: "9",
//         name: "Sweet Potato Fries",
//         quantity: 1,
//         price: 6.99,
//         status: OrderStatus.pending,
//         scheduledDay: "Vrydag",
//       ),
//       OrderItem(
//         id: "10",
//         name: "Chocolate Shake",
//         quantity: 1,
//         price: 5.99,
//         status: OrderStatus.pending,
//         scheduledDay: "Vrydag",
//       ),
//     ],
//     scheduledDays: ["Vrydag"],
//     status: OrderStatus.pending,
//     createdAt: DateTime.parse("2025-09-11T13:20:00Z"),
//     totalAmount: 26.97,
//   ),
//   Order(
//     id: "ORD-005",
//     customerEmail: "david.wilson@email.com",
//     items: [
//       OrderItem(
//         id: "11",
//         name: "Beef Steak",
//         quantity: 1,
//         price: 24.99,
//         status: OrderStatus.readyDelivery,
//         scheduledDay: "Donderdag",
//       ),
//       OrderItem(
//         id: "12",
//         name: "Mashed Potatoes",
//         quantity: 1,
//         price: 7.99,
//         status: OrderStatus.readyDelivery,
//         scheduledDay: "Donderdag",
//       ),
//       OrderItem(
//         id: "13",
//         name: "Grilled Vegetables",
//         quantity: 1,
//         price: 9.99,
//         status: OrderStatus.readyFetch,
//         scheduledDay: "Donderdag",
//       ),
//     ],
//     scheduledDays: ["Donderdag"],
//     status: OrderStatus.readyDelivery,
//     createdAt: DateTime.parse("2025-09-11T12:00:00Z"),
//     totalAmount: 42.97,
//   ),
//   Order(
//     id: "ORD-006",
//     customerEmail: "lisa.anderson@email.com",
//     items: [
//       OrderItem(
//         id: "14",
//         name: "Thai Green Curry",
//         quantity: 2,
//         price: 17.99,
//         status: OrderStatus.preparing,
//         scheduledDay: "Woensdag",
//       ),
//       OrderItem(
//         id: "15",
//         name: "Jasmine Rice",
//         quantity: 2,
//         price: 3.99,
//         status: OrderStatus.preparing,
//         scheduledDay: "Woensdag",
//       ),
//     ],
//     scheduledDays: ["Woensdag"],
//     status: OrderStatus.preparing,
//     createdAt: DateTime.parse("2025-09-10T16:30:00Z"),
//     totalAmount: 43.96,
//   ),
//   Order(
//     id: "ORD-007",
//     customerEmail: "alex.martinez@email.com",
//     items: [
//       OrderItem(
//         id: "16",
//         name: "Spaghetti Bolognese",
//         quantity: 1,
//         price: 19.99,
//         status: OrderStatus.delivered,
//         scheduledDay: "Maandag",
//       ),
//       OrderItem(
//         id: "17",
//         name: "Garlic Bread",
//         quantity: 2,
//         price: 4.99,
//         status: OrderStatus.delivered,
//         scheduledDay: "Maandag",
//       ),
//     ],
//     scheduledDays: ["Maandag"],
//     status: OrderStatus.delivered,
//     createdAt: DateTime.parse("2025-09-09T19:30:00Z"),
//     totalAmount: 29.97,
//   ),
//   Order(
//     id: "ORD-008",
//     customerEmail: "jennifer.white@email.com",
//     items: [
//       OrderItem(
//         id: "18",
//         name: "Chicken Alfredo",
//         quantity: 1,
//         price: 21.99,
//         status: OrderStatus.delivered,
//         scheduledDay: "Dinsdag",
//       ),
//       OrderItem(
//         id: "19",
//         name: "Caesar Salad",
//         quantity: 1,
//         price: 12.99,
//         status: OrderStatus.delivered,
//         scheduledDay: "Dinsdag",
//       ),
//       OrderItem(
//         id: "20",
//         name: "Cheesecake",
//         quantity: 1,
//         price: 7.99,
//         status: OrderStatus.delivered,
//         scheduledDay: "Dinsdag",
//       ),
//     ],
//     scheduledDays: ["Dinsdag"],
//     status: OrderStatus.delivered,
//     createdAt: DateTime.parse("2025-09-08T14:15:00Z"),
//     totalAmount: 42.97,
//   ),
//   Order(
//     id: "ORD-009",
//     customerEmail: "robert.taylor@email.com",
//     items: [
//       OrderItem(
//         id: "21",
//         name: "BBQ Ribs",
//         quantity: 1,
//         price: 26.99,
//         status: OrderStatus.delivered,
//         scheduledDay: "Sondag",
//       ),
//       OrderItem(
//         id: "22",
//         name: "Mac and Cheese",
//         quantity: 1,
//         price: 8.99,
//         status: OrderStatus.delivered,
//         scheduledDay: "Sondag",
//       ),
//     ],
//     scheduledDays: ["Sondag"],
//     status: OrderStatus.delivered,
//     createdAt: DateTime.parse("2025-09-07T17:45:00Z"),
//     totalAmount: 35.98,
//   ),
// ];
